# config/settings.py
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"
MODELS_DIR = DATA_DIR / "models"

for d in [RAW_DIR, PROCESSED_DIR, MODELS_DIR]:
    d.mkdir(parents=True, exist_ok=True)

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
NEWS_API_KEY = os.getenv("NEWS_API_KEY", "")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
DATABASE_URL = os.getenv("DATABASE_URL", f"sqlite:///{DATA_DIR}/stocks.db")

HISTORY_YEARS = 3
MAX_STOCKS = int(os.getenv("MAX_STOCKS", 200))
DATA_REFRESH_MINUTES = int(os.getenv("DATA_REFRESH_INTERVAL", 60))

TRAIN_TEST_SPLIT = 0.8
PREDICTION_HORIZON_DAYS = 1
FORECAST_DAYS = [1, 7, 30, 90]
RANDOM_STATE = 42
N_JOBS = -1

RSI_PERIOD = 14
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
BB_PERIOD = 20
BB_STD = 2
SMA_PERIODS = [20, 50, 200]
EMA_PERIODS = [9, 21, 55]

HIGH_RISK_VOLATILITY = 0.35
MEDIUM_RISK_VOLATILITY = 0.20

SENTIMENT_POSITIVE_THRESHOLD = 0.2
SENTIMENT_NEGATIVE_THRESHOLD = -0.2
NEWS_LOOKBACK_DAYS = 7
MAX_NEWS_PER_STOCK = 20

BUY_CONFIDENCE_THRESHOLD = 0.65
SELL_CONFIDENCE_THRESHOLD = 0.40

GROQ_MODEL = "llama3-70b-8192"
GROQ_MAX_TOKENS = 1024

SECTORS = {
    "Banking": ["HDFCBANK", "ICICIBANK", "KOTAKBANK", "AXISBANK", "SBIN", "BANKBARODA", "PNB", "INDUSINDBK"],
    "IT": ["TCS", "INFY", "WIPRO", "HCLTECH", "TECHM", "LTIM", "MPHASIS", "PERSISTENT"],
    "Pharma": ["SUNPHARMA", "DRREDDY", "CIPLA", "DIVISLAB", "BIOCON", "TORNTPHARM", "AUROPHARMA"],
    "FMCG": ["HINDUNILVR", "ITC", "NESTLEIND", "BRITANNIA", "DABUR", "MARICO", "COLPAL"],
    "Energy": ["RELIANCE", "ONGC", "BPCL", "IOC", "GAIL", "NTPC", "POWERGRID", "ADANIGREEN"],
    "Auto": ["MARUTI", "TATAMOTORS", "M&M", "BAJAJ-AUTO", "EICHERMOT", "HEROMOTOCO", "TVSMOTOR"],
    "Telecom": ["BHARTIARTL", "IDEA", "TATACOMM"],
    "Metal": ["TATASTEEL", "HINDALCO", "JSWSTEEL", "SAIL", "VEDL"],
    "Finance": ["BAJFINANCE", "BAJAJFINSV", "CHOLAFIN", "MUTHOOTFIN", "PFC", "RECLTD"],
}
